### PR TITLE
Changed Makefiles

### PR DESCRIPTION
**Pull request by cwaldm**
I changed the Makefiles so that they do not write into the core DY* repo anymore.
This independence is needed for the CI for this repo. (And is also cleaner.)

### CODE REVIEW

**Comment by fabian-hk** [comment]
I think if you go this route, you should include Comparse and DY* as git submodules. This is probably also needed for the CI and it simplifies the setup for new users. Maybe this would even allow us to reuse the original DY* Makefile without copying it.

**Comment by TWal** [comment]
For the CI, on DY* we rely on Nix to have reproducible builds, and the various versions (Comparse, DY*, F*) are pinned in the `flake.lock` file, so no submodules are needed for CI.
I started writing a nix build for this repo, I shall push it soon (and after that, adding CI is a small amount of work).

**Comment by TWal** [comment]
I have added the nix stuff, that will verify the examples and run them. Interestingly, we run examples in parallel, because each Makefile will write the .depend and this messes things up… This probably needs fixing, but for new it works™
I will add the github runners thing later.

**Comment by TWal** [comment]
Looks like CI works and there is a green :)

**Comment by TWal** [comment]
I think this is mergeable, although it's not perfect:
- For some reason when adding the targets `check-Online` etc in `.PHONY`, the `check` rule doesn't run the rule `check-Online` (as a dependency), I haven't figured out why. I guess it would be cleaner to have a proper `.PHONY` rule but well, we can do that later
- When running a test, this writes into the `.depend` meaning we can't run tests in parallel. This should probably be fixed at some point, but we can run tests sequentially for now (I have configured the nix build to do that)
- I haven't tested, but the F* code running the protocol should fail if some test run returns `None`, so that CI becomes red. But we can also look into this later

The idea being that it's better to have imperfect CI than not having any

**Review by TWal — APPROVED** [review]

**Comment by cwaldm** [comment]
Great! Thank so much!
I agree and will merge it for now. It can be improved later if needed.

**Pull request merged**
